const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const contracts=fs.readFileSync(path.join(root,'api/contracts.js'),'utf8');
const status=fs.readFileSync(path.join(root,'api/status.js'),'utf8');
const readme=fs.readFileSync(path.join(root,'README.md'),'utf8');
let n=0,fail=[];function t(name,cond){n++;if(!cond)fail.push(name)}
// 49 structural / integration checks
[
['v0.7 title',html.includes('GACS Career v0.7 LIVE')],['airlabs input',html.includes('id="airlabsKey"')],['fr24 input',html.includes('id="fr24Key"')],['airlabs save action',html.includes("a==='saveAirlabs'")],['airlabs clear',html.includes("a==='clearAirlabs'")],['airlabs signup',html.includes('https://airlabs.co/signup')],['fr24 official',html.includes('https://fr24api.flightradar24.com/')],['navigraph request',html.includes('developers.navigraph.com/docs/request-access')],['say local endpoint',html.includes('http://localhost:43117/flightJSON')],['ready live',html.includes('async function readyLive')],['airlabs header',html.includes('X-GACS-AIRLABS-KEY')],['accept live',html.includes('acceptLiveContract')],['no fake notice',html.includes('aucune donnée fictive')],['cutoff text',html.includes('≥ 2h30')],['gate column',html.includes('<th>Gate</th>')],['simbrief',html.includes('fetchOFP')],['weather',html.includes('weatherNow')],['local airlabs storage',html.includes('gacs_airlabs_key')],['local fr24 storage',html.includes('gacs_fr24_key')],['say detected storage',html.includes('gacs_say_detected')],['contracts airlabs endpoint',contracts.includes('airlabs.co/api/v9/schedules')],['contracts 150min',contracts.includes('150*60000')],['contracts fleet set',contracts.includes('FLEET=new Set')],['contracts A388',contracts.includes("'A388'")],['contracts A359',contracts.includes("'A359'")],['contracts A35K',contracts.includes("'A35K'")],['contracts A339',contracts.includes("'A339'")],['contracts A343',contracts.includes("'A343'")],['contracts B772',contracts.includes("'B772'")],['contracts B77W',contracts.includes("'B77W'")],['contracts B78X',contracts.includes("'B78X'")],['contracts A20N',contracts.includes("'A20N'")],['contracts A21N',contracts.includes("'A21N'")],['contracts B738',contracts.includes("'B738'")],['contracts B739',contracts.includes("'B739'")],['contracts CRJ9',contracts.includes("'CRJ9'")],['contracts C25C',contracts.includes("'C25C'")],['reject cancelled',contracts.includes("'cancelled'")],['reject landed',contracts.includes("'landed'")],['sort contracts',contracts.includes('.sort(')],['limit 30',contracts.includes('.slice(0,30)')],['status client configurable',status.includes('clientConfigurable:true')],['status bridge required',status.includes('bridgeRequired:true')],['status simbrief',status.includes('Latest OFP fetch actif')],['readme airlabs',readme.includes('AirLabs Schedules')],['readme FR24 optional',readme.includes('FR24 est optionnel')],['readme navigraph',readme.includes('Navigraph')],['manifest exists',fs.existsSync(path.join(root,'manifest.webmanifest'))],['service worker exists',fs.existsSync(path.join(root,'sw.js'))]
].forEach(x=>t(...x));
// 250 boundary/filter simulations: every minute from +0 to +249, exact cutoff behavior.
const now=Date.now(); for(let m=0;m<250;m++){const admissible=(now+m*60000)>=now+150*60000;t(`cutoff minute ${m}`,admissible===(m>=150));}
if(n!==299)fail.push(`expected 299 tests, got ${n}`);
console.log(`GACS v0.7 quality: ${n-fail.length}/${n} PASS`);if(fail.length){console.error(fail.join('\n'));process.exit(1)}
