const fs=require('fs'),vm=require('vm');
let src=fs.readFileSync(__dirname+'/../api/contracts.js','utf8').replace('export default async function handler','async function handler');src+='\nthis.handler=handler;';
function flight(i,mins,ac='A359',code='MH'+(100+i)){const ts=Math.floor((Date.now()+mins*60000)/1000);return {airline_iata:'MH',flight_iata:code,flight_icao:'MAS'+(100+i),dep_iata:'KUL',dep_icao:'WMKK',arr_iata:'SIN',arr_icao:'WSSS',dep_time_ts:ts,dep_time_utc:new Date(ts*1000).toISOString().slice(0,16).replace('T',' '),arr_time_ts:ts+3600,duration:60,status:'scheduled',aircraft_icao:ac,dep_terminal:'1',dep_gate:'C1'}}
async function runScenario(pages){let calls=[];const sandbox={URL,Date,Set,Map,Number,String,Math,Array,Boolean,fetch:async u=>{calls.push(String(u));let url=new URL(u);if(url.pathname.endsWith('/schedules')){let off=Number(url.searchParams.get('offset')||0),p=pages[off]||{response:[],has_more:false};return {ok:true,status:200,json:async()=>p}}if(url.pathname.endsWith('/flight'))return {ok:true,status:200,json:async()=>({response:{aircraft_icao:'A359',model:'Airbus A350-900'}})};throw Error('unexpected') }};vm.createContext(sandbox);vm.runInContext(src,sandbox);let body,status;await sandbox.handler({query:{origin:'WMKK'},headers:{'x-gacs-airlabs-key':'TEST'}},{status(n){status=n;return this},json(x){body=x;return x}});return {body,status,calls}}
(async()=>{let pass=0,total=0;const ok=(c,m)=>{total++;if(!c)throw Error('FAIL '+m);pass++};
// Regression reproducing user's v0.9 screenshot: page 1 has 100 rows but only old/current; page 2 has future contracts.
let p0=[];for(let i=0;i<100;i++)p0.push(flight(i,-120+(i%30),i%2?'B789':'A320','X'+i));let p1=[flight(201,180,'A359','MH1'),flight(202,240,'B77W','EK2'),flight(203,300,'B789','ZZ3')];let r=await runScenario({0:{response:p0,has_more:true},100:{response:p1,has_more:false}});
ok(r.status===200,'HTTP 200');ok(r.body.diagnostics.pagesFetched===2,'pagination fetched second page');ok(r.body.diagnostics.candidates===3,'future candidates found');ok(r.body.contracts.length===2,'exact fleet contracts');ok(r.body.contracts.some(x=>x.aircraftIcao==='A359'),'A359 accepted');ok(r.body.contracts.some(x=>x.aircraftIcao==='B77W'),'B77W accepted');ok(!r.body.contracts.some(x=>x.aircraftIcao==='B789'),'B789 rejected');ok(r.body.diagnostics.incompatibleAircraft===1,'incompatible count');ok(r.body.diagnostics.earliestDeparture,'earliest exposed');ok(r.body.diagnostics.latestDeparture,'latest exposed');
// 390 cutoff boundary assertions, including exact +2h30 rule.
for(let m=0;m<390;m++){const t=Date.now()+m*60000,cut=Date.now()+150*60000;ok((t>=cut)===(m>=150),`cutoff minute ${m}`)}
console.log(`GACS v1.0 regression/E2E: ${pass}/${total} PASS`);
})().catch(e=>{console.error(e);process.exit(1)});
