const FLEET=new Set(['A388','A359','A35K','A339','A343','B772','B77W','B78X','A20N','A21N','B738','B739','CRJ9','C25C']);
const IATA={RJAA:'NRT',RJTT:'HND',OMDB:'DXB',OTHH:'DOH',OMAA:'AUH',WSSS:'SIN',WMKK:'KUL',VTBS:'BKK',VHHH:'HKG',LFPG:'CDG',EGLL:'LHR',LSZH:'ZRH',LEBL:'BCN',LFRS:'NTE',LFMN:'NCE',YSSY:'SYD'};
const AIRLINES={EK:'Emirates',UAE:'Emirates',QR:'Qatar Airways',QTR:'Qatar Airways',EY:'Etihad Airways',ETD:'Etihad Airways',SQ:'Singapore Airlines',SIA:'Singapore Airlines',MH:'Malaysia Airlines',MAS:'Malaysia Airlines',TG:'Thai Airways',THA:'Thai Airways',JL:'Japan Airlines',JAL:'Japan Airlines',NH:'ANA',ANA:'ANA',QF:'Qantas',QFA:'Qantas',GA:'Garuda Indonesia',GIA:'Garuda Indonesia',PR:'Philippine Airlines',PAL:'Philippine Airlines',AI:'Air India',AIC:'Air India'};
const CLIENT=new Set(['EK','UAE','QR','QTR','EY','ETD']);
const REJECT_STATUS=new Set(['cancelled','landed']);
const clean=s=>String(s||'').trim().toUpperCase();
const epoch=v=>{const n=Number(v);return Number.isFinite(n)&&n>0?n*1000:NaN};
const utc=v=>{if(!v)return NaN;const s=String(v).trim();const t=Date.parse(s.includes('T')?s:(s.replace(' ','T')+'Z'));return Number.isFinite(t)?t:NaN};
// UTC/timestamp ONLY for filtering. dep_time is airport-local display text and must never be Date.parse'd by the Vercel timezone.
function schedTime(f){for(const v of [epoch(f.dep_time_ts),utc(f.dep_time_utc),epoch(f.dep_estimated_ts),utc(f.dep_estimated_utc)])if(Number.isFinite(v))return v;return NaN}
function base(f){return {flight:f.flight_iata||f.flight_icao||f.flight_number||'—',flightIcao:f.flight_icao||'',airlineCode:f.airline_iata||f.airline_icao||'',airline:AIRLINES[clean(f.airline_iata)]||AIRLINES[clean(f.airline_icao)]||f.airline_iata||f.airline_icao||'Compagnie non renseignée',operatorFlight:f.cs_flight_iata||'',operatorCode:f.cs_airline_iata||'',originIata:f.dep_iata||'',originIcao:f.dep_icao||'',destinationIata:f.arr_iata||'',destinationIcao:f.arr_icao||'',stdLocal:f.dep_time||'',stdUtc:f.dep_time_utc||'',staLocal:f.arr_time||'',staUtc:f.arr_time_utc||'',stdTs:schedTime(f),depTerminal:f.dep_terminal||'',depGate:f.dep_gate||'',arrTerminal:f.arr_terminal||'',arrGate:f.arr_gate||'',durationMin:Number(f.duration)||null,status:String(f.status||'scheduled').toLowerCase(),aircraftIcao:clean(f.aircraft_icao),aircraftModel:f.model||'',registration:f.reg_number||'',dataStatus:'LIVE',source:'AirLabs Schedules'}}
function merge(f,d={}){const b=base(f);return {...b,flightIcao:d.flight_icao||b.flightIcao,aircraftIcao:clean(d.aircraft_icao||b.aircraftIcao),aircraftModel:d.model||b.aircraftModel,registration:d.reg_number||b.registration,depTerminal:b.depTerminal||d.dep_terminal||'',depGate:b.depGate||d.dep_gate||'',arrTerminal:b.arrTerminal||d.arr_terminal||'',arrGate:b.arrGate||d.arr_gate||'',source:d.aircraft_icao?'AirLabs Schedules + Flight Info':b.source}}
async function airlabs(path,params,key){const u=new URL('https://airlabs.co/api/v9/'+path);for(const[k,v]of Object.entries(params))if(v!==''&&v!=null)u.searchParams.set(k,String(v));u.searchParams.set('api_key',key);const r=await fetch(u,{headers:{Accept:'application/json'}});let d={};try{d=await r.json()}catch{}if(!r.ok||d.error){const msg=d.error?.message||d.error?.code||`HTTP ${r.status}`;throw new Error(`AirLabs ${path}: ${msg}`)}return d.response}
function dedupe(rows){const seen=new Set();return rows.filter(f=>{const physical=f.cs_flight_iata||f.flight_iata||f.flight_icao||f.flight_number;const k=`${physical}|${f.dep_time_ts||f.dep_time_utc||f.dep_time||''}|${f.arr_iata||f.arr_icao||''}`;if(seen.has(k))return false;seen.add(k);return true})}
function sameFlightInstance(schedule,detail){if(!detail)return false;const sDep=clean(schedule.dep_iata||schedule.dep_icao),dDep=clean(detail.dep_iata||detail.dep_icao);const sArr=clean(schedule.arr_iata||schedule.arr_icao),dArr=clean(detail.arr_iata||detail.arr_icao);if(sDep&&dDep&&sDep!==dDep)return false;if(sArr&&dArr&&sArr!==dArr)return false;const a=schedTime(schedule),b=schedTime(detail);if(Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a-b)>6*3600000)return false;return true}
function preScore(f){let s=0;const c=clean(f.airline_iata||f.airline_icao);if(CLIENT.has(c))s+=100;const dur=Number(f.duration)||0;if(dur>=300)s+=30;else if(dur>=150)s+=15;if(f.aircraft_icao&&FLEET.has(clean(f.aircraft_icao)))s+=200;return s}
function contractScore(f,now){let s=50;if(CLIENT.has(clean(f.airlineCode)))s+=35;if(f.durationMin>=300)s+=12;if(f.depGate)s+=3;if(f.registration)s+=2;const hrs=(f.stdTs-now)/36e5;if(hrs>=3&&hrs<=8)s+=8;return Math.round(s)}
function pay(f){const h=Math.max(1,(f.durationMin||180)/60);const wide=new Set(['A388','A359','A35K','A339','A343','B772','B77W','B78X']).has(f.aircraftIcao);return Math.round((320+h*(wide?145:95)+(CLIENT.has(clean(f.airlineCode))?180:0))/10)*10}
function priority(score){return score>=95?'P1 · PRIORITAIRE':score>=78?'P2 · RECOMMANDÉ':'P3 · STANDARD'}
async function getSchedulePages(originIata,originIcao,key,cutoff){const all=[];let previousFingerprint='';let pages=0;for(const offset of [0,100,200,300]){const params={[originIata?'dep_iata':'dep_icao']:originIata||originIcao,limit:100,offset};const page=await airlabs('schedules',params,key);const rows=Array.isArray(page)?page:[];pages++;if(!rows.length)break;const fingerprint=rows.slice(0,5).map(x=>`${x.flight_iata}|${x.dep_time_ts||x.dep_time_utc||x.dep_time}`).join(';');if(offset>0&&fingerprint===previousFingerprint)break;previousFingerprint=fingerprint;all.push(...rows);const future=dedupe(all).filter(x=>{const t=schedTime(x);return Number.isFinite(t)&&t>=cutoff&&!REJECT_STATUS.has(String(x.status||'').toLowerCase())});if(future.length>=35)break;if(rows.length<100)break}return {rows:all,pages}}
export default async function handler(req,res){
 const origin=clean(req.query.origin);if(!/^[A-Z0-9]{4}$/.test(origin))return res.status(400).json({error:'Origin ICAO invalide'});
 const key=req.headers['x-gacs-airlabs-key']||process.env.AIRLABS_API_KEY||'';if(!key)return res.status(200).json({setupRequired:true,contracts:[],message:'Clé AirLabs requise.'});
 const now=Date.now(),cutoff=now+150*60000,iata=IATA[origin]||'';
 try{
  const paged=await getSchedulePages(iata,origin,key,cutoff);const all=paged.rows;
  const diag={received:all.length,pages:paged.pages,deduplicated:0,validTime:0,beforeCutoff:0,cancelledOrLanded:0,candidates:0,directAircraft:0,flightInfoAttempted:0,flightInfoSuccess:0,flightInfoMismatch:0,flightInfoErrors:0,missingAircraft:0,incompatibleAircraft:0,accepted:0,flightInfoErrorSample:'',firstReceivedUtc:'',lastReceivedUtc:''};
  const unique=dedupe(all);diag.deduplicated=unique.length;const timed=unique.map(f=>({f,t:schedTime(f)})).filter(x=>Number.isFinite(x.t)).sort((a,b)=>a.t-b.t);diag.validTime=timed.length;if(timed.length){diag.firstReceivedUtc=new Date(timed[0].t).toISOString();diag.lastReceivedUtc=new Date(timed[timed.length-1].t).toISOString()}
  const candidates=[];for(const {f,t} of timed){if(t<cutoff){diag.beforeCutoff++;continue}if(REJECT_STATUS.has(String(f.status||'').toLowerCase())){diag.cancelledOrLanded++;continue}candidates.push(f)}
  diag.candidates=candidates.length;diag.directAircraft=candidates.filter(f=>clean(f.aircraft_icao)).length;candidates.sort((a,b)=>preScore(b)-preScore(a)||schedTime(a)-schedTime(b));
  // Enrich only the best untyped candidates. A /flight result is accepted only if route/time match this scheduled instance.
  const enrichTargets=candidates.filter(f=>!clean(f.aircraft_icao)).slice(0,24);const details=new Map();
  for(const f of enrichTargets){const id=f.cs_flight_iata||f.flight_iata||f.flight_icao;if(!id)continue;diag.flightInfoAttempted++;try{const d=await airlabs('flight',id===f.flight_icao?{flight_icao:id}:{flight_iata:id},key);if(d&&sameFlightInstance(f,d)){details.set(f,d);if(d.aircraft_icao)diag.flightInfoSuccess++}else if(d)diag.flightInfoMismatch++}catch(e){diag.flightInfoErrors++;if(!diag.flightInfoErrorSample)diag.flightInfoErrorSample=e.message}}
  const rows=candidates.map(f=>merge(f,details.get(f)||{}));const contracts=[],rejected=[];
  for(const f of rows){if(!f.aircraftIcao){diag.missingAircraft++;rejected.push({...f,rejectReason:'TYPE NON PUBLIÉ / NON RÉCUPÉRÉ'});continue}if(!FLEET.has(f.aircraftIcao)){diag.incompatibleAircraft++;rejected.push({...f,rejectReason:`${f.aircraftIcao} · HORS FLOTTE`});continue}const score=contractScore(f,now);contracts.push({...f,score,priority:priority(score),salaryGacs:pay(f),salaryStatus:'SCÉNARIO GACS',sceneryStatus:'À VÉRIFIER'})}
  contracts.sort((a,b)=>b.score-a.score||a.stdTs-b.stdTs);diag.accepted=contracts.length;
  let message=contracts.length?`${contracts.length} contrat(s) GACS admissible(s).`:`Aucun contrat exact trouvé : ${diag.missingAircraft} sans type exploitable, ${diag.incompatibleAircraft} hors flotte.`;
  if(!diag.candidates&&diag.validTime)message+=` AirLabs a renvoyé une fenêtre ${diag.firstReceivedUtc} → ${diag.lastReceivedUtc}, sans départ ≥ +2h30. Le board ne prétend pas qu'il n'existe aucun vol : la fenêtre fournisseur est insuffisante.`;
  return res.status(200).json({origin,originIata:iata,provider:'AirLabs v9',generatedAt:new Date(now).toISOString(),cutoff:new Date(cutoff).toISOString(),contracts:contracts.slice(0,30),diagnostics:diag,rejected:rejected.slice(0,30),message});
 }catch(e){return res.status(502).json({error:e.message,diagnostics:{provider:'AirLabs v9',failed:true}})}
}
